### ISSUE TITLE
Segmentation Fault when running ./Demo

### ISSUE THREAD

**Issue by WayfaringBloke** [adrianiainlam/mouse-tracker-for-cubism#1]
Basically what the title says, running in WSL if that could be issue but I don't think so since other OpenGL stuff works. Happy to provide more info but I'm unsure what to add. 

Also because I was installing on a clean distro I found `sudo apt install unzip autoconf` was also needed to compile.

Thanks in advance if you have any idea how to fix this :).

**Comment by adrianiainlam** [comment]
Hi @WayfaringBloke, if you can install `gdb` and provide a backtrace that would be very helpful.

After installing it, when you run the command you can prepend `gdb` in front of the command to start the debugger. Then just type `run` and it should run until the segfault occurs. Then type `bt` for the backtrace, and paste it here.

Thanks.

**Comment by adrianiainlam** [comment]
By the way, this may or may not be related -- a backtrace is the best way to tell.
https://github.com/Live2D/CubismNativeFramework/pull/30/files

**Comment by adrianiainlam** [comment]
Also, if you can edit example/demo_build/scripts/make_gcc and change the line with `-D CMAKE_BUILD_TYPE=Release` to `-D CMAKE_BUILD_TYPE=Debug`, then run this make_gcc script (not the build.sh scripts) to rebuild it before running gdb, that would be even more helpful.
Thanks.

**Comment by WayfaringBloke** [comment]
Remade it in a VM of 20.04 Ubuntu and it works fine sorry.
